[build]
# Utiliser notre Dockerfile pour avoir ldapsearch
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
startCommand = "node init-certificates.js && npm start"

[[services]]
name = "b2-smime"
port = 3001

# Variables d'environnement
[env]
CERT_DIR = "/app/certificates"
USE_LDAPJS = "true"  # Utiliser ldapjs (pure Node.js) au lieu de ldapsearch
NODE_ENV = "production"

# Configuration du volume persistant
[[volumes]]
mount = "/app/certificates"
name = "certificates"